python src/main.py \
    --seed=SEED \
    --model_idx=MODEL_IDX \
    --rule_injection=full \
    --scene_idx=SCENE_IDX \
    --num_players=1 \
    --export_data \
    --concat_policy=simple \
    --include_functions \
    --frequency_penalty=0.5 \
    --presence_penalty=0.5 \
    --temperature=1.0 \
    --top_p=0.8